### ISSUE TITLE
Bug na extenção

### ISSUE THREAD

**Issue by aquila0101** [DesignLiquido/vscode#57]
### Executei esse código na extensão

```
programa
{
	
inteiro numero,a1,a2,a3,a4

	funcao inicio()
	{
		escreva("Quantas pessoas Foram ao Jogo de Futebol?  ")
		leia(numero)
        a1 = numero*10/100
		a2 = numero*50/100
        
        
        escreva("\n A Renda de pessoas A R$ 5 foi: ", a1)
        escreva("\n A Renda de pessoas A R$ 10 foi: ", a2)
	}
}

```

###  e tive esse erro:

```
Quantas pessoas Foram ao Jogo de Futebol?
Error: Operadores precisam ser números.
	at InterpretadorPortugolStudioComDepuracao2.verificarOperandosNumeros (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:59978:15)
	at InterpretadorPortugolStudioComDepuracao2.visitarExpressaoBinaria (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60019:18)
	at async Binario.aceitar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:48776:16)
	at async InterpretadorPortugolStudioComDepuracao2.avaliar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60860:16)
	at async InterpretadorPortugolStudioComDepuracao2.visitarExpressaoDeAtribuicao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60142:23)
	at async Atribuir.aceitar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:48754:16)
	at async InterpretadorPortugolStudioComDepuracao2.avaliar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60860:16)
	at async InterpretadorPortugolStudioComDepuracao2.visitarDeclaracaoDeExpressao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60154:16)
	at async Expressao.aceitar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:49839:16)
	at async InterpretadorPortugolStudioComDepuracao2.executar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:61189:16)
	at async InterpretadorPortugolStudioComDepuracao2.executarUltimoEscopoComandoContinuar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:61117:31)
	at async InterpretadorPortugolStudioComDepuracao2.executarBloco (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:61027:20)
	at async DeleguaFuncao.chamar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:51549:30)
	at async InterpretadorPortugolStudioComDepuracao2.visitarExpressaoDeChamada (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60122:44)
	at async InterpretadorPortugolStudioComDepuracao2.visitarExpressaoDeChamada (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60881:25)
	at async Chamada.aceitar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:48825:16)
	at async InterpretadorPortugolStudioComDepuracao2.avaliar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60860:16)
	at async InterpretadorPortugolStudioComDepuracao2.visitarDeclaracaoDeExpressao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:60154:16)
	at async Expressao.aceitar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:49839:16)
	at async InterpretadorPortugolStudioComDepuracao2.executar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:61189:16)
	at async InterpretadorPortugolStudioComDepuracao2.executarUltimoEscopoComandoContinuar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:61117:31)
	at async InterpretadorPortugolStudioComDepuracao2.instrucaoContinuarInterpretacao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:61149:9)
	at async InterpretadorPortugolStudioComDepuracao2.instrucaoContinuarInterpretacao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.16-universal/dist/extensao.js:61239:33)
```
### sendo que no portugol studio tive esse resultado:

Quantas pessoas Foram ao Jogo de Futebol?  1200

 A Renda de pessoas A R$ 5 foi: 120
 A Renda de pessoas A R$ 10 foi: 600
Programa finalizado. Tempo de execução: 3557 milissegundos

**Comment by aquila0101** [comment]
![Captura de tela de 2024-04-02 17-15-30](https://github.com/DesignLiquido/vscode/assets/162712945/c1af8b52-3ce7-43ae-bd2f-1ed47b932a4c)
![Captura de tela de 2024-04-02 17-16-02](https://github.com/DesignLiquido/vscode/assets/162712945/9af83ca9-0411-4b76-8fd3-2bfafc2e4624)

**Comment by leonelsanchesdasilva** [comment]
@aquila0101 Obrigado por reportar. Aviso por aqui quando estiver pronto.
